### ISSUE TITLE
Update to visjs version 4.17

### ISSUE THREAD

**Issue by seveves** [seveves/ng2-vis#10]
Update the visjs typings and update services where needed

**Comment by hypery2k** [comment]
vis 4.17 does not work correctly on Safari, just to mention it ;) The timeline component is not rendering items in the timeline

**Comment by seveves** [comment]
Thank you for the information @hyper2k ... is there an issue referencing this problem in visjs?

**Comment by hypery2k** [comment]
Didn't found one

**Comment by seveves** [comment]
ng2-vis 0.0.4 uses latest version 4.17.0
