### ISSUE TITLE
Could not find module 'vis'.

### ISSUE THREAD

**Issue by sisirak** [seveves/ng2-vis#13]
Hi 
I am trying to get the ng2-vis timeline working in one of my projects and have added as  dependency (    "ng2-vis": "0.0.2").  But during the tsc compilation I am getting the error **"Could not find module 'vis'"** in components/timeline/index.d.ts
Noted that you have fixed this issue in 0.0.1-6. I found that if I clone the project and compile it works perfectly. Issue is when I tried to use this in a different project by adding as a dependency.

Thank you
Sisira

**Comment by seveves** [comment]
I'm also using the timeline in a demo project where I am using the 0.0.2 version and bundling the whole thing with webpack. I didn't encounter any problems there but I will check this again tomorrow. Is it possible that you provide your code?

**Comment by sisirak** [comment]
Thank you seveves, I can share the code. I am using angular-quickstart@1.0.0 seed for VS2015.

**Comment by seveves** [comment]
@sisirak I've created a fresh angular2 project with the angular-cli and ng2-vis@0.0.2 works fine there. Can you check if the 0.0.2 version is really installed and can you provide the tsc command and config so I can check this one too? Do you have a link to the angular-quickstart seed ... it seems like that there are many different :)

**Comment by sisirak** [comment]
@seveves please find attached the files (NG1.zip) you request from angular-quickstart seed for visual studio project. Please let me know if you need any more files. I have attached the files listing as well. If you are fine, could you share the fresh project you did which is working with me as I am new to angular I may have done some basic mistakes.

[NG1.zip](https://github.com/seveves/ng2-vis/files/593770/NG1.zip)

![ng1rootfolder](https://cloud.githubusercontent.com/assets/23420543/20335266/976e33ee-abda-11e6-82b4-7b395ff8db61.PNG)

**Comment by seveves** [comment]
I saw that you are using systemjs and this is something I've not tested yet. I've checked the systemjs builder config and saw that it fails on building.  I've packed a version and you can download it from here: https://drive.google.com/open?id=0B4zBN-z3dqXzaUh5YjhwLWZYN1U

you can install and test this version with: npm install ng2-vis-0.0.3-develop.tgz

Please let me know if this version fixes your problem.

**Comment by sisirak** [comment]
Thank you sevenes, I will try this out an update you.

**Comment by seveves** [comment]
The possible fix for this issue is also included in the new [0.0.3 release](https://www.npmjs.com/package/ng2-vis)

**Comment by sisirak** [comment]
Thank you @seveves , now without any issue it works. We can close the issue.

**Comment by seveves** [comment]
I'm glad to hear ... thank you for keeping me up to date!

**Comment by AndrewLang** [comment]
I use systemjs, I still have this issue with version 0.0.4.

**Comment by seveves** [comment]
@AndrewLang share your code and maybe someone can help. Maybe it is possible for @sisirak to share his project settings too
