### ISSUE TITLE
Problem including ng2-vis in Angular2

### ISSUE THREAD

**Issue by KevKo1990** [seveves/ng2-vis#14]
Hi,

I just wanted to include your code into my library and I hang at the moment at an error I do not understand.

I included in my project vis.js 4.16.1 properly. Furthermore I included in my Angular2 application your demo code examples and do not encounter any more issues with wrong folder settings etc.

You have maybe a clue what the problem is?

Thanks!
![ng2_vis](https://cloud.githubusercontent.com/assets/12497609/20458197/4fe2c79e-ae9e-11e6-9641-80edc1d55f1c.PNG)

**Comment by KevKo1990** [comment]
I found the error - I tried to include vis.js via my angular-cli.json. That caused some trouble.
Furthermore, I still need the vis.css in my angular-cli.json, else the timeline example makes trouble...

You can close this.

**Comment by seveves** [comment]
I'm glad that the problem is solved. In my sample project there is no need to reference the vis.css because webpack knows how to load the css files. I'll bet you can get help from the angular-cli community on this problem :)
