### ISSUE TITLE
itemover function for the timeline

### ISSUE THREAD

**Issue by KevKo1990** [seveves/ng2-vis#16]
Hi,

I tried to use the itemover function from the timeline.

I thought I have to register it as the click event... however nothings happen!

I put the following code into the timelineInitialized() function:

```
this.visTimelineService.on(this.visTimeline, 'itemover');

this.visTimelineService.itemover
      .subscribe((eventData: any[]) => {
        console.log(eventData);
});
```

Is this not ready yet? Or did I implement something wrong? Thank you!

**Comment by seveves** [comment]
Hi @KevKo1990 ... I'm sorry but the itemover event is new in [visjs 4.17.0](https://github.com/almende/vis/blob/develop/HISTORY.md#timeline--graph2d). It is accidentally already availabe in the VisTimelineService. I am going to resolve this issue asap with issue #10

**Comment by seveves** [comment]
@KevKo1990 Please let me know if the itemover works for you now with the latest version 0.0.4

**Comment by KevKo1990** [comment]
Works!
Keep up the great work, thank you!
