### ISSUE TITLE
Timeline  entries not rendered on Safari

### ISSUE THREAD

**Issue by hypery2k** [seveves/ng2-vis#18]
in latest ng2-vis no entries are rendered on Safari 10, on chrome its working

**Comment by mojoaxel** [comment]
@hypery2k Please [create an issue](https://github.com/almende/vis/issues/new) in the vis.js library directly.

**Comment by seveves** [comment]
as @mojoaxel has already mentioned: this is not a bug that I can solve in this repository. Feel free to create an issue over at the visjs project and reference it here.
