### ISSUE TITLE
How to access the getViewPosition() method

### ISSUE THREAD

**Issue by daniel4thsource** [seveves/ng2-vis#19]
Hi great work on the project!

I was wondering how I can access the getViewPosition() method from the "public API". I was looking into the code and wondering how I can have access to the VisNetwork object to call the method. 

Keep up the good work!

**Comment by seveves** [comment]
Looks like it is missing. I'm going to add this method till next weekend.

**Comment by daniel4thsource** [comment]
Awesome! Thanks!

**Comment by seveves** [comment]
@daniel4thsource I've updated [ng2-vis to version 0.0.5](https://www.npmjs.com/package/ng2-vis). I've also updated to the latest angular version ... I hope this is not a big deal for you. Let me know if this version fixes your problem so we can close this issue (:

**Comment by daniel4thsource** [comment]
Worked like a Charm! Thank you very much! You da man!
