### ISSUE TITLE
Node/Edge level options

### ISSUE THREAD

**Issue by bpellens** [seveves/ng2-vis#25]
Hello, 

I really like your angular 2 components so far. I do have a quick question if I may. Is it possible to independent options to the nodes or the edges. When going through the code I can only see option set at the network level. What I want to achieve is different stylings (e.g. colors) for different types of nodes.

Thank you for the feedback,

Kind Regards,

Bram

**Comment by seveves** [comment]
I'm very busy at the moment but this is related to #23. The TypeScript definitions are not up to date and incomplete. I hope I can fix this by updating to the new vis typings. Maybe next weekend. Till then you can try to create your nodes as 'any' types and cast it to VisNode before adding to the dataset.
`let myColorNode = { id: 'someId', label: 'someLabel', color: 'someColor' };
 networkData.nodes.add(myColorNode as VisNode); // networkData is of type VisNetworkData`

**Comment by bpellens** [comment]
Thank you very much for the feedback. It is working perfectly! I am closing this question then.

**Comment by krystlih** [comment]
Does this work for VisEdges as well?

**Comment by seveves** [comment]
Sure ... should be quite similar
