### ISSUE TITLE
Building causes error with AOT

### ISSUE THREAD

**Issue by GingerGeek** [seveves/ng2-vis#26]
Upon attempting to build this project with AOT with angular-cli I get the following errors, any idea?

```
zed@gingerninja ~/Development/project.example.com  (master *)$ ng build --target=production --environment=production
Hash: 289f9755f27fde876d85
Time: 11082ms
chunk    {0} polyfills.d270cc2992ad57a6bff0.bundle.js (polyfills) 222 kB {4} [initial] [rendered]
chunk    {1} main.06ee6a03687560961e81.bundle.js (main) 2.1 kB {3} [initial] [rendered]
chunk    {2} styles.40713392d4d9083ea2df.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.29e2472b36186853adf4.bundle.js (vendor) 1.06 MB [initial] [rendered]
chunk    {4} inline.dee33d806992d75a5a27.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Could not resolve vis relative to /Users/zed/Development/project.example.com/node_modules/ng2-vis/components/timeline/index.d.ts., resolving symbol VisTimelineItems in /Users/zed/Development/project.example.com/node_modules/ng2-vis/components/timeline/index.d.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/Users/zed/Development/project.example.com/src'
 @ ./src/main.ts 5:0-74
 @ multi ./src/main.ts
zed@gingerninja ~/Development/project.example.com  (master *)$
```

**Comment by seveves** [comment]
Hm I never tried this lib with an AOT project but this library provides the ng2-vis.metadata.json and this file does not include the "VisTimelineItems". I'm not sure if this is the problem because the error says that it is more likely a problem with the import of the 'vis' library.
I really need to update to the latest angular version and use the @types/vis instead of my own type definitions.
Is you project open source so we can test an updated version of ng2-vis with AOT?

**Comment by GingerGeek** [comment]
It is not, however I will quickly create a test project :)

**Comment by GingerGeek** [comment]
This repo has the issue: [GingerGeek/vis-aot-failure](https://github.com/GingerGeek/vis-aot-failure)

It was created with latest angular 2. Get the error with any of:
```
ng serve --aot
ng build --aot
ng build --target=production
```

**Comment by joel00** [comment]
Another issue when try to **ng build --prod** works well in dev mode

"@angular/core": "~2.4.0" 
"@angular/cli": "^1.0.0-rc.0"
"ng2-vis": "0.0.5"

Unexpected value 'VisNetworkDirective in ../node_modules/ng2-vis/components/network/vis-network.directive.d.ts' declared by the module 'VisModule in ../node_modules/ng2-vis/ng2-vis.d.ts'

Any idea?

**Comment by seveves** [comment]
Currently not working with AOT. I'm currently trying to fix this and also using the new type defs from DT. I hope I can get this running asap

**Comment by GingerGeek** [comment]
Try building with --prod --aot false
That should fix your issue?

**Comment by joel00** [comment]
@GingerGeek Yes it works, although I don't think it's a good idea to disable AOT

**Comment by GingerGeek** [comment]
That's why we have this issue open 😉

**Comment by itslenny** [comment]
This same issue causes xi18n to crash. It does not have an option to disable AOT this is a complete blocker for me.

This is the stack trace you get when running `ng xi18n`:

```
An error occured during the i18n extraction:
Error: Error encountered resolving symbol values statically. Could not resolve vis relative to .../node_modules/ng2-vis/components/timeline/index.d.ts., resolving symbol VisTimelineItems in .../node_modules/ng2-vis/components/timeline/index.d.ts
    at simplifyInContext (...\node_modules\@angular\compiler\bundles\compiler.umd.js:25569:27)
    at StaticReflector.simplify (...\node_modules\@angular\compiler\bundles\compiler.umd.js:25581:17)
    at StaticReflector.annotations (...\node_modules\@angular\compiler\bundles\compiler.umd.js:25073:84)
    at NgModuleResolver.resolve (...\node_modules\@angular\compiler\bundles\compiler.umd.js:17557:86)
    at CompileMetadataResolver.getNgModuleMetadata (...\node_modules\@angular\compiler\bundles\compiler.umd.js:18058:64)
    at addNgModule (...\node_modules\@angular\compiler\bundles\compiler.umd.js:24839:62)
    at ...\node_modules\@angular\compiler\bundles\compiler.umd.js:24850:18
    at Array.forEach (native)
    at _createNgModules (...\node_modules\@angular\compiler\bundles\compiler.umd.js:24849:30)
    at analyzeNgModules (...\node_modules\@angular\compiler\bundles\compiler.umd.js:24724:18)
    at analyzeAndValidateNgModules (...\node_modules\@angular\compiler\bundles\compiler.umd.js:24734:39)
    at Extractor.extract (...\node_modules\@angular\compiler\bundles\compiler.umd.js:27589:22)
    at Extractor.extractBundle (...\node_modules\@angular\compiler-cli\src\extractor.js:40:33)
    at Extractor.extract (...\node_modules\@angular\compiler-cli\src\extractor.js:30:34)
    at Function.NgTools_InternalApi_NG_2.extractI18n (...\node_modules\@angular\compiler-cli\src\ngtools_api.js:92:26)
    at _donePromise.Promise.resolve.then (...\node_modules\@ngtools\webpack\src\extract_i18n_plugin.js:113:59)
```

**Comment by itslenny** [comment]
I got that previous error to go away by manually installing the type definitions for vis `npm i @types/vis`, but now I have a new error. This error occurs when running `ng xi18n` or `ng build -prod`

```
ERROR in Unexpected value 'VisNetworkDirective in .../node_modules/ng2-vis/components/network/vis-network.directive.d.ts'
declared by the module 'VisModule in .../node_modules/ng2-vis/ng2-vis.d.ts'

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/main/app.module.ngfactory'
in 'C:\Users\leurba\Source\Repos\Dynamics365-HCM-TalentEngagement\src'
 @ ./src/main.ts 9:0-79
 @ multi ./src/main.ts
```

**Comment by itslenny** [comment]
The issue appears to just be an angular version mismatch. Also, I get an error about `vis` not being defined which can be resolved by simply running `npm i @types/vis`.

I just submitted a PR that fixes the issue for me locally.

**Comment by seveves** [comment]
@itslenny thank you for the PR. I'm glad that this fixes the issue for you. I will fix the lint errors with the next version. I also will merge this PR this weekend and release a new version for you (maybe I have to tag it as pre-release but that should be fine).
Can someone of the others ( @GingerGeek or @joel00 ) confirm that AOT compilation works with these changes?

**Comment by joel00** [comment]
@seveves Negative. "Same error: ERROR in Unexpected value 'VisNetworkDirective in ...."

using: angular-cli rc2
updating angular 2.4.9 and installing @type/vis

**Comment by seveves** [comment]
@joel00 ok thank you ... I'm on it right now

**Comment by seveves** [comment]
Anybody up for testing this: ```npm install ng2-vis@next```
I've added the ng2-vis module to a ng-cli project and it worked using ng build --aot

Make sure that you are installing version ng2-vis@0.0.6-pre.1 for your tests ... if this version works for you I'll publish it as 0.0.6.

**Comment by GingerGeek** [comment]
Works for me after removing any reference to __vis and updating a few other types ;) 👍

**Comment by seveves** [comment]
But these references are in your own code and not related to ng2-vis?

**Comment by seveves** [comment]
I've tested a bit more with a local ng-cli project and all seems fine. So I published the 0.0.6 release.
Hope it works well for you @itslenny and @joel00 too

**Comment by GingerGeek** [comment]
Yes - in my code, but they were referencing stuff within ng2-vis, so it introduces some breaking changes

**Comment by seveves** [comment]
I'm sorry for these breaking changes but as long as it works now with AOT compilation it was worth the change 😸 (next change will be the update to vis 4.19 and angular 4)

**Comment by GingerGeek** [comment]
Yeah it wasn't anything major, only took 30s to fix - well worth it for AOT compilation

Many thanks for all this 😁

**Comment by joel00** [comment]
@seveves with 0.0.6 AOT is working now. Thanks for your time

**Comment by seveves** [comment]
Thank you for using it and reporting bugs and being patient 😁 ... if you like this project then feel free to give it a star ✌
