### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by Dunky13** [seveves/ng2-vis#41]
The latest push was on March 18th - both dev and master branch. I'm wondering if there is still (active) development going on for this package?

**Comment by seveves** [comment]
Not really ... the project needs a rewrite with best practices published by the angular team. For example I would use the yeoman generator-angular2-library next time because it plays nicely with all the module formats and AOT. Another thing is that the visjs Type Definitions are improving slowly and I don't see much interest by the visjs team to improve their library to work nicely with typescript. If anyone wants to maintain this repository and keep it alive then let me know :)

**Comment by RingoKam** [comment]
Hi @seveves, I am interested in maintaining the project and keeping it alive. How can I help?

**Comment by seveves** [comment]
Like I said in my previous comment. The project should be converted to a project that has been created with f.e. a generator that bundles in all the several module formats and helps with AOT compilation.

As a second step you should update to the latest visjs version and its type definitions.

Let me know if you are still interested and I'll grant you the needed permissions.

**Comment by RingoKam** [comment]
Got it! I am looking into using _yeoman generator-angular2-library_ you mentioned above, any other resource that you found helpful?

**Comment by seveves** [comment]
I think these are the most important points. Of course [Minko Gechev](http://blog.mgechev.com/2017/01/21/distributing-an-angular-library-aot-ngc-types/)'s blog is always a good read.

**Comment by anvial** [comment]
Hi, All 

I'm also interested in using this project. So I can help to test and to develop. 

@RingoKam any updates?

**Comment by RingoKam** [comment]
hey @anvial, I started the project a weekend ago with the yo package @seveves  suggested. Ran into bunch of built errors. I will try to look at it again tonight.

**Comment by seveves** [comment]
@RingoKam feel free to post your build errors. Maybe I can help a bit. Also let me know if you need extra contributors to help you, like @anvial f.e.

**Comment by seveves** [comment]
beside the generator-angular2-library way there is also https://github.com/dherges/ng-packagr

**Comment by RingoKam** [comment]
Thanks! I will take a look at ng-packagr. 

I used the one you posted couple weeks ago _yeoman generator-angular2-library_ for a project at work, and it worked fine. I think the built issue I ran into last time was relate to something else.

**Comment by tatsujb** [comment]
update?

**Comment by hypery2k** [comment]
you can check this project: https://www.npmjs.com/package/ngx-vis

It's my forked of this repo with Angular 5+ Support
